name: Build QEMU Windows Installer

concurrency: 
  group: ${{ ( github.event_name == 'push' && 'test' ) || 'release' }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  qemu_repo: physics-enthusiast/qemu
  branch: win9p-rebase

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      version: ${{ steps.get-version.outputs.ver }}
      tag_name: ${{ steps.generate_env_vars.outputs.tag_name }}
    steps:
      - name: Get version
        id: get-version
        run: |
          echo "ver=$(curl https://raw.githubusercontent.com/${{ env.qemu_repo }}/${{ env.branch }}/VERSION)" >> $GITHUB_OUTPUT
      - name: Generate environmental variables
        id: generate_env_vars
        run: |
          echo "tag_name=qemu-${{ ( github.event_name == 'push' && 'test' ) || steps.get-version.outputs.ver }}" >> $GITHUB_OUTPUT
          echo "release_name=${{ ( github.event_name == 'push' && format('Test Build {0}', steps.get-version.outputs.ver) ) || format('Build {0}', steps.get-version.outputs.ver) }}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - name: Check for existing tag
        id: check-tag
        run: |
          if gh release view "${{ steps.generate_env_vars.outputs.tag_name }}" -R ${{ github.repository }}; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Clear previous release
        run: gh release delete ${{ steps.generate_env_vars.outputs.tag_name }} --yes --cleanup-tag -R ${{ github.repository }}
        if: ${{ steps.check-tag.outputs.exists == 'true' }}
      - name: Create new release
        run: |
          gh release create ${{ steps.generate_env_vars.outputs.tag_name }} --title "${{ steps.generate_env_vars.outputs.release_name }}" --generate-notes=false --draft=false --latest=false --prerelease=true

  builds:
    needs: release
    name: Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Build Dockerfile
        run: |
          docker build https://github.com/${{ env.qemu_repo }}.git#${{ env.branch }} --file ./tests/docker/dockerfiles/fedora-win64-cross.docker --tag=cross-compile:latest
      - name: Compile QEMU
        uses: addnab/docker-run-action@v3
        with:
          image: cross-compile:latest
          shell: bash
          options: -v ${{ github.workspace }}:/var/qemu
          run: |
            git config --global http.version HTTP/1.1
            git config --global http.postBuffer 157286400
            git clone https://github.com/${{ env.qemu_repo }}.git
            cd qemu
            git checkout ${{ env.branch }}
            mkdir build
            cd build
            ../configure --disable-docs --disable-plugins --disable-user --enable-sdl --enable-gtk --enable-slirp --enable-fdt=internal --target-list="x86_64-softmmu i386-softmmu aarch64-softmmu arm-softmmu riscv64-softmmu riscv32-softmmu" $QEMU_CONFIGURE_OPTS $EXTRA_CONFIGURE_OPTS
            make -j$(expr $(nproc) + 1)
            make -j$(expr $(nproc) + 1) installer
            mv qemu-setup-${{ needs.release.outputs.version }}.exe /var/qemu/qemu-setup.exe
      - name: Upload Installer
        run: |
          gh release upload ${{ needs.release.outputs.tag_name }} qemu-setup.exe --repo ${{ github.repository }}
      - name: Set as latest
        run: |
          gh release edit ${{ needs.release.outputs.tag_name }} --draft=false --prerelease=false --latest=${{ github.event_name == 'workflow_dispatch' }} --repo ${{ github.repository }}
          
